#spring.application.name=backendp
#server.port=3333

#spring.datasource.url=jdbc:mysql://localhost:3306/backendp
#spring.datasource.username=root
#spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/backendp
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=3333